language: java
jdk:
- openjdk8
env:
  global:
  - CC_TEST_REPORTER_ID=45ea9dad0d4eb801ab7e281b2edceebc1204d5a4741dbb61b428af8639ddf2a3
  - secure: CZftTqZEmtrF2FlWteXQcRxI+mp3SwZhyHJvsBNcvlGWMiCJBjdR/S+amA7YBPxuwhdDihMFhQvQylcaN8fky9Oxkeifn+sqM6IZbSu0tslcHoT6SJF/7bOnHFjcw/unaphxIGiLlv0yOVTfQ9Zm2L/oF69yJ46ZhtkWDyoiNVgVVbwjYOuR+b6HqCevqsIvvVh8KujrdqH7xotEkSLjqsPs18AwshBYnbpCyAWRcTD2qqSGGT/c21tqyLmCbe4Ztf8JJAK8h9v+o7EDMDbdYodI2y4MddAi5xCRbnl8Seb7IGweT2h0K+qVPus8B7clDtqEiDW0+uqvIjGgpFx1x5+FGNrkymEmh7tyMabqyGLKE0Fo5igGg2qvnITuoeuji+GzV2T5k7Gv9613OMRRUNfk1zfkJkKW5dorcaQS1mSQy6LaS7DTpauk8Iwo+Te3HEHeWVJ8UdsnySsTd6tk9vsqiYUn6YokWElOSqWH4/0rsgNAgIUcRK3RLJiTgqrHoGs0fcNxSlDOmswN/GgUoAGCnS1lU/daYM644BPwnNTegbZA4yn9Qup2aoUbaLU8PrTtkEuTPOlK3ftTI91XOsMXttR48YS3jrGryw7v8rDaEiYqH4Yo0OA900S+Wv+Gj0EW2EO+AV0pP0baM53CyKVFeg440cg5ZdCkfCQ93cc=
  - secure: iI3ciC0PEasNU2wWqInD7Vm5fr2v+GnAb5qpX/d6s2FOjHMFLZmtsAiWGNz8bpHj+aY82V5hVzSbzfwL/yHXyBjNd0tfpUXk6QMyZpfWMfImqnXUBHMRFTyJWOddUWbJ/uPi9JBKJnlqCAmN7t8WBWvI73AAht/EGwA/h7dX/A+bEVKBg49t+0jnnL4glDb6GFz88u5pLh79QqZ/24k39axKs2JspxXJBUkcpjDCFSvPFWFtggmRdhkwoP7cXmn1hnwK2cpU0+S3J/rGwYx+JBBAPJLGKQKkHAhnytc3JoZH1dKA5jvMbnXbQch0jAtEn8C0F9G9qZ6n2Mx9b1o9qvmp9QN7acvKtrtZPxGeKqgvBrjRDaB1/KzUQhGQxsdxisQMmCwJQjztskkDOBrHjoLQmUTeTxAwwHZcEJlAz8XHx6YCCVLUqLH4mRPQJYudjWedVlwyn6N/kCpRfi4DRi/BF99qSdkzbi8MPuq4nIlO43HmOUG2SwSIgWLOfYqWWQyl3DPUFN7HAaN12+7T9+YCYBGzQaqpajeozPQrOSEnz2WejnLTodgfVIlrbeI1r9ywqSd7riWHZi5Aek1vO/aVWAfz7nFsA+Dh69VJ7WcBRYsXk2HQ/gxbTY541nb9M6JOfLLwh49j2vaZNfvZpfpnEV2cRQxtV7uHA5e6YAs=
  - secure: dk/qphutnxUiyVs1ALyWWV/ZalerMUsDRV3/eSbtWTc+cEG1xdcT2Qdj3sl7NRH257MqWmQCa25BOE+Ze29ll61nTpKqzpCpvnZnHaszWOEojK8E9jYYaC2GWQT2HBnoITj+6XkoxhmPR4qhHF4bzqLmBL1vaqn4YjFFyM6p1dQSD5XLTxSfakjbJIZw+4q7XImmeMsc3kD7GRGfjRXQE8/FgEosF58blu+rFfL48jQOubUjGSzNEjlMaJbGM+kyqn10BpIQqa2LQ07Ub7+2JeWYrk7BkVoq2myA3SDhvkxs9ezi1vgFy2mlTD0xeqPHJ71Jy/7ZYH4UovtRWZgD3jw5sp5tJ4LbrW+f4zmMCHg+TkbZz+6RQiZBnxEsytiRDcnBDXUbaL8aUAIYrIhEFJBaYdmfTnz8/1k1weSyiRs1l4hi9zpeqpyvTBDyju8dz/WkbEqzQFkKAadp/RVHmkERVycod3ztbhaVW476VN40QU8K2qv+oGHGPSRouUjMrmqJWeeTTq9a3ozHW5E5heCPGhlv9z4FHvGq+r5iFooO35epf/mkT9CDXblLdzlsyGe5uRTHc4vBtSE7LD6PjISJSt4D8ut+SxWhA9pbvoH9YXawae86PUf4Y5QRUDqfvBP3Tr2w+XoytT1cSqsdY494IQKjCU/DcJAGUMzSR/o=
install:
- mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- ".travis/before-script.sh"
script:
- mvn test
after_script:
- "./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml"
- "./cc-test-reporter upload-coverage -d"
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
- provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: trickl/model-oanda
    all_branches: true
- provider: releases
  api_key:
    secure: fIprgeLah/zaqST6AF+V25bAm+bO+XXBtqY7BVp3znkVG6RTKGp5MFDziUyV3l74RNLkH57Jdpi7jYNjwf6h3XWVWdHrqjCPGfDwIHtOJS9mH7oS5UG0Q2KzIICHpd7/r2ebKI4l90dwOGSY8BBTIUmD3WRtY5B4X3gZEehAks45c/v3Am3jyRJ2KGd6XbXH7Md08npN6p4Zyzl1zv4qOrH0WAUpuuuDQ/kn0Mn7xALaEEl2jBrmvUZFw25xDUMNmHGMdD8eHSVC2lR/d7g4u1qGC9nvoT8LqvHErzlxVCyaiFhk+Z1KpKeHmtidywzabx8LrrNCzuY8xTb3eY2ESnRVg7U1DiDS1P75XVtITIYIRf9iIESVzIjmsfA2+0jzBzAzqNl3OHutlfKa09RPTayt51H7J3ZGGRyBgEvkQhngDUf9nOoTrJ25COXd7eVWWzpKaliRMNL6XpOm4fadKJ8h0kaRW7HovCeD3qPCpT/QWgOTzffYpTHKmTytiM45rap4HA1z4NRMkHerxng6VdHCEM2sLZcV+M2CxioX2yf2+nj1WWWZey+pz9QPeQFetm8PFaAt/eSNNAEqrhbWGf9UIRlZWbF2rzSeHlHw7w+biDYCyVPxA9IJneYCBVeBm2sSfFqKUnitD3sT7ENohU5fhfn1qReRktDFpPJlPn4=
  file: ".travis.yml"
  on:
    repo: trickl/model-oanda
