language: java
jdk:
- openjdk8
env:
  global:
  - CC_TEST_REPORTER_ID=45ea9dad0d4eb801ab7e281b2edceebc1204d5a4741dbb61b428af8639ddf2a3
  - secure: V8dXQVbl1OCzZ1bE5ipWTnOB5O5S93xFlciCQisyfkPCcER98gNCr03rNyYuXUWImJlTL0QTGCqgMJ2stIapMq3QeRuuXak7ZJUsLDZPqdHFpCznxgxYokieQ368p7uR+rmahaoPRDnwYji/kPsUtQeWf3+Q7Lo8RbqQcNUVtmIZEn5oks2BuGj8h32Q5y/3W/fJ7LfxBgw5alpppChFD/N8d2BtESD+5iSb0WezwyxE6+4AI5KFy+CbSE3K9MBVxpzoiVvl1799JYxfpMEC2uDVMhX+t3dMOHKgXtwnpqKlU9GDBqj9xfxMuT0TFo5zw6FFLnPoP4aUpR5bAZSy8pfDDeqLWBQtYfKUTWMDy5VL8/C0ef7cUb7Y844u3RTPLXOcp8joB5fUtFfq4DhbKjQcN5wausAsKo00FHPwA4d8LK479fRM81+1SNiPgfz6SlTCV83RVet+3jyg43JZBTL7lpfebkzRuBP/g2AXu1YeqWKtxq2FqdhCUsX8fIQRiJkt7gaiZVzH9FDMdyopGFL2yEJrAD7TRgjL9iMZMJWn9GR0US29EFsCxmIbVwCYuxk93zX1+xMFBBAQ56iCcZUO59LHj/+rMnrAW1tM3f+J8s3hyKK0rcksv6U5/HX2AfSVRwj7+77i8JZVyGVYXgMM44+CxecPXz9bMv2XLL4=
  - secure: NiTnqV58egfjv9R0/rrU4Q0XjBs/QI8XmpCb9abes+p2G7KHdxaN3ab2zY3nhpUZD7k3XScrOlsi2JV33oW5cdGzIW4yKZ53DM36YIw7sAcAOQbXsVgx4/9cmBvvwHLshWI3uww8X9bG5bejS/U5th+5jAq+E70TG37Mxojyic9VWtxwAIQC+ill5Kk28u05HmlRtHwIVwguWZMT7jmflJ3/WtbJoggRX6YeCBwqYVLPYuXBy4PBMFyX2Rf0Crnp14d/Kfg1raROFAzh+7jkHJHSw3pgGGQUqe0qG90VT9RCWiTbjL7rA4IPDAcqReVJ7zwIXYMktVimDlJPBt30SInF90vNmVGZ0LJytL3G01ijw2bS1oOCMqB5CzAK7Fo+5/kvDQSG8xK+NAHD/DMPmNIrhyNG5po6rzsmLWj0rJ7G8P2AtIrPFR9tmRLGwUcp8if7TWOxv3J3iNetTv3jAfbajtZaT9MrsX8irNMLYcfNX5AIqZs9iPbmoQuF9IQqUI72zCIf9279FBvnypjudNxsSUsWh+Q6AQbKedcx6xgrbOAz/M8cB447iOzgGcRS+br/iEghPAD91NGEHvfneoypdQMUO9azEbTzBk8HItdvuqBBuncM4C5a/Dij/ruPCmDMEdlYT/FEnw8cLfgJnrA7i+v8QECDcpCNSi579go=
  - secure: S0wiUSiiPsVx4X9VVSvLfj86w/rkqU/vsUn/yjxYQ/7Uj0sp9jjU01BQafUEv9xoZrcTgyXENKPNl5GGVesMBwPTXPWyoY3pi5na5M4WezfvMmLk5QcjTufgyaQYyMqgqAuK1JOdL+nd76nPdAwHR3oHY72gug8X2Gli5H0WopifnsghuMg+YYnS2A2pn820inHyjfmH0+m5OHxJd2rqSX0qH2GyHn29W3pbG0iDGlXvXa50fftvlrQ//LOWlfRPTLBPFwkc1aGuhzsQEG38XU0YSmJVvKOECMekLkIARx3+OdYtS3ay16gvqU+T1gaTlLmn5xKy7XWGQGOJwIS9z10ONw7b/taqVmsvkceZ403nFPm8/szKmcr5rD8NeLAe9Qx23h9Y/SYdpaAdtKed1Tlp7TWUfgywp774qZqSBDyd2ldUCTo+x0FTtyIhDhcey86tzZZd9bjYSX4qiM0NuhT96TaHeWT39Pi+jxMznGDIc+0j4wToshh5G9/uJZ5EhvzbsGybwlWEd63QxSj2Ku89BBSykTUmQXMbDVO3DhfKw3CM+ku7Ow4TsaA2tI1aR8/gyln4bI0/tSBgyUgefhUNChoAYZoJZIqLEdt4OrbjbiBBtkV8ns+lKRrMObWalHXlE8fVgCEiC9RBUaKZxlIAWNCdEgRm1w6+C0xSkRU=
install:
- mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- ".travis/before-script.sh"
script:
- mvn test
after_script:
- "./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml"
- "./cc-test-reporter upload-coverage -d"
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
- provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: trickl/model-oanda
    all_branches: true
- provider: releases
  api_key:
    secure: fIprgeLah/zaqST6AF+V25bAm+bO+XXBtqY7BVp3znkVG6RTKGp5MFDziUyV3l74RNLkH57Jdpi7jYNjwf6h3XWVWdHrqjCPGfDwIHtOJS9mH7oS5UG0Q2KzIICHpd7/r2ebKI4l90dwOGSY8BBTIUmD3WRtY5B4X3gZEehAks45c/v3Am3jyRJ2KGd6XbXH7Md08npN6p4Zyzl1zv4qOrH0WAUpuuuDQ/kn0Mn7xALaEEl2jBrmvUZFw25xDUMNmHGMdD8eHSVC2lR/d7g4u1qGC9nvoT8LqvHErzlxVCyaiFhk+Z1KpKeHmtidywzabx8LrrNCzuY8xTb3eY2ESnRVg7U1DiDS1P75XVtITIYIRf9iIESVzIjmsfA2+0jzBzAzqNl3OHutlfKa09RPTayt51H7J3ZGGRyBgEvkQhngDUf9nOoTrJ25COXd7eVWWzpKaliRMNL6XpOm4fadKJ8h0kaRW7HovCeD3qPCpT/QWgOTzffYpTHKmTytiM45rap4HA1z4NRMkHerxng6VdHCEM2sLZcV+M2CxioX2yf2+nj1WWWZey+pz9QPeQFetm8PFaAt/eSNNAEqrhbWGf9UIRlZWbF2rzSeHlHw7w+biDYCyVPxA9IJneYCBVeBm2sSfFqKUnitD3sT7ENohU5fhfn1qReRktDFpPJlPn4=
  file: ".travis.yml"
  on:
    repo: trickl/model-oanda
